# Test your FastAPI endpoints

POST http://127.0.0.1:8000/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

###

POST http://127.0.0.1:8000/auth/register
Accept: application/json
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}
